### ISSUE TITLE
[Feature Request]: More operations on the widget.

### ISSUE THREAD

**Issue by tiepcha** [fibelatti/photo-widget#115]
### Describe your idea

In another app, I saw a very useful and convenient setting that allows three actions to be performed on the widget. They divided the widget frame into three parts: the two side sections for moving to the next image or going back to the previous one, and the middle section to either open the widget app or view the image in full screen. 

### Describe how you think it could work

I think this feature is very convenient and worth implementing.

### Additional context

It would be even better if we could customize the actions for all three sections.

**Comment by fibelatti** [comment]
Hi @tiepcha, thanks for submitting your idea! That's not the first time someone asks for something similar, so I'll definitely consider this change for an upcoming release.

**Comment by fibelatti** [comment]
@tiepcha this change is being shipping with version 1.17.0, already available on GitHub and rolling out on the Play Store soon.

At first only the middle action can be customized, with the sides being used for switching photos. I'll consider making all 3 actions customizable in the future.

Thanks for suggesting the change!
