### ISSUE TITLE
[Bug]: Unable to migrate already created widget between launchers

### ISSUE THREAD

**Issue by Username1-a** [fibelatti/photo-widget#116]
### Describe the problem

1. Create "Photos" source widget. For example, I picked marked as "Favorites" photos from "Google Photos" through the DocumentUI file picker, then app was downloading those photos for quite some time. Now it appears that the photos stored in app's cache after downloading and the widget is saved in "My widgets" bottom tab, so there shouldn't be any problem adding the same widget to a different launcher, but:

2. After changing home launcher, and trying to re-add that same widget using the app ("Edit" or "Duplicate" widget and then "Add to home screen"), is shows as empty widget with red "missing file" icon on a home screen (see screenshot)

### Device model

Redmi Note 10 Pro

### Android version

Android 13 QPR3, Custom ROM

### App version

1.16.2

### Additional information

![Screenshot_20241026-191057_Lawnchair](https://github.com/user-attachments/assets/0ee8d1d2-9208-4a9a-9bb9-6ec1accfa2ce)

I use Lawnchair 14 launcher just moved to a different version (Lawnchair 14 Beta 2 to 14 Beta 3 Play Store) instead, so wanted to migrate the widget instead of just redownloading it all over again. Hope anything could be done to resolve this issue

**Comment by fibelatti** [comment]
Hi @Username1-a, thanks for reporting this issue. The details provided should help with trying to reproduce the issue on my end to fix it. I'll get back to you once I have more information.

**Comment by fibelatti** [comment]
@Username1-a after a brief investigation, it seems that there's a problem with the "Duplicate" function overall, and it's not related to the launcher migration. I'll have it patched in the next release which should be coming out soon.
