### ISSUE TITLE
More theme options

### ISSUE THREAD

**Issue by Fuoxden** [fibelatti/photo-widget#120]
### Describe your idea

the app is super good! but I do think it would be nice to change the accent colors, and have a black options for amoled screens, so a pure black option

### Describe how you think it could work

in the app right now, when you go to 'app colors' there is only 2 options, how bout there's more? like maybe a list of premade ones, like maybe a bright orange, dark pink, light pink, dark green, light green, dark red, red, ect, or have a slider where you could change it yourself!

**Comment by fibelatti** [comment]
Hi @Fuoxden, thanks for sharing your thoughts about the app and submitting your idea!

I'll think about it, but I can't guarantee it will be a priority. You see, I don't expect people to spend a lot of time _in the app_. I want to make it easy to set up widgets, and once it's done, you should hardly ever have to come back (unless you’re changing them often, of course 😅). That said, the dynamic colors follow your device style tinting, so the app always matches it.

Having a true black option is valid, and I'll consider adding that one first.

**Comment by fibelatti** [comment]
Hi @Fuoxden, the true black theme option will be included in the next app release, coming between today and tomorrow. I'll close this issue for now, but know that I haven't discarded adding more color theme options in the future. Thanks for your suggestions.
