### ISSUE TITLE
Excluding certain photos from your widgets

### ISSUE THREAD

**Issue by Fuoxden** [fibelatti/photo-widget#122]
### Describe your idea

When you scan a folder, it will add **all** the photos in that folder, but what if you didn't want certain photos in the app but not want to outright delete them? Why not have an option to exclude and maybe even delete?

### Describe how you think it could work

You go to my widgets, view/edit, then you hold down on one or more photos to select an option to exclude, and maybe even more options! like maybe a delete to outright delete it, and or maybe a share button!

**Comment by fibelatti** [comment]
Thanks for submitting this idea @Fuoxden, excluding certain photos from the widget can definitely work so I'll consider that for an upcoming update. However, the app doesn't have permission (or the intention) to work as a file manager so permanently deleting the photo from your file system won't be an option.

**Comment by Fuoxden** [comment]
Okey! That's fine, I didn't expect deleting files to be an option or even intention, I am happy that Excluding photos is being considered :)

**Comment by fibelatti** [comment]
Hi @Fuoxden, this feature will be included in the next app release. Thanks for your suggestion, I'll leave this issue open until a version that contains the change is released.

**Comment by Fuoxden** [comment]
Can't wait! :]

**Comment by fibelatti** [comment]
Hi @Fuoxden, this feature is included in version 1.19.0, released today. Thanks for your suggestion!

**Comment by Fuoxden** [comment]
Wooo! Thank you for considering and Implementing my suggestion!
