### ISSUE TITLE
[Bug]: Image not shown at full resolution

### ISSUE THREAD

**Issue by bilogic** [fibelatti/photo-widget#123]
### Describe the problem

1. I link this widget to a map which contains small text
2. I want to see the map in full resolution when I tap on it
3. Single photos can only `View photo in full screen` when tapped
4. However, the map loads with blurred text even though I enabled `View original photo`, i.e. it was resized smaller
5. Possible to show the map at original resolution?
6. If not, make `View in gallery` also available to single photos? 
7. Or `Open with...`, like Shortcut Image https://shortcut-image.en.softonic.com/android

### Device model

Samsung A50

### Android version

Android 10

### App version

1.18.1

**Comment by fibelatti** [comment]
Hi @bilogic, thanks for opening this issue!

When an image is added to a widget, it’s automatically resized to a maximum of 3840x3840 during import. As you correctly guessed, the `View original photo` option displays this resized version, not the true original. In this context, "original" refers to the image without additional modifications like rotation or cropping.

Originally, this resizing was intended to minimize device storage usage. However, over time, the maximum dimensions were increased to accommodate cases like yours. At this point, the benefit of reduced storage usage is marginal, as we now accept images up to 4K resolution.

Let me explore the best way to address this. I’m considering removing the resizing limit entirely, allowing the widget to retain the original dimensions. If implemented, the `View original photo` feature would then work as you’re expecting.

**Comment by fibelatti** [comment]
Hi @bilogic, photos will no longer be resized from the next app version onwards. This means that using `View in full screen` with `View original photo` enabled should work as you're expecting. Please note that you will have to recreate a widget to import photos with their original size instead.

Thanks for the suggestion, I'll leave the issue open until a version containing the change is released.

**Comment by bilogic** [comment]
Wow thanks! Is there a beta that I can download and test out?

**Comment by bilogic** [comment]
I noticed you use the word "import" on your latest commit comments.

Are the selected photos copied somewhere else to be used by the widget, or is it always loaded from the source?

**Comment by fibelatti** [comment]
> I noticed you use the word "import" on your latest commit comments.
> 
> Are the selected photos copied somewhere else to be used by the widget, or is it always loaded from the source?

@bilogic when choosing photos, they are copied over to the internal app storage. This way, widgets won't break if the original photo is deleted. When choosing folders, the reference to the folder is saved instead and photos are loaded from the source, except if you crop and/or rotate, in which case the modified version of the photo is saved to the internal app storage.

As for a beta, there's no option for that currently.

**Comment by fibelatti** [comment]
Hi @bilogic, a new setting to control the image quality is included in version 1.19.0, released today. Thanks for your suggestion!

**Comment by bilogic** [comment]
thanks, i don't see it in Play store yet
