### ISSUE TITLE
[Feature Request]: Access "Allow setting alarms and reminders"-permission from within the app

### ISSUE THREAD

**Issue by HeldGames** [fibelatti/photo-widget#130]
### Describe your idea

Feature request ported from previous issue https://github.com/fibelatti/photo-widget/issues/129.

Currently the allow permission button, is only accessible once, when you first download the app. This is a minor oversigt, as one might need to enable it later. Therefor I think it would be great to have the a "Allow setting alarms and reminders" button inside the settings

### Describe how you think it could work

Go to settings -> "permissions" (or something like that) -> Allow alarm and reminder permission (Sub text: This allows for more accurate timers)

Press it, and it will take you to the same page, as the current implementation does

**Comment by fibelatti** [comment]
Hi @HeldGames, a new setting was included in version 1.19.0, released today. It only shows for people who haven't given the permission yet, so you might not see it. Thanks for your suggestion!
