### ISSUE TITLE
FEATURE REQUEST: Select album or folder rather than individual images

### ISSUE THREAD

**Issue by hughwilliams94** [fibelatti/photo-widget#31]
Hey thanks for the project it's a great little widget! It is a little tedious having to select all of the images individually. I am imagining a mechanism to select a folder of images to flick through randomly rather than picking individual images. Is this something you would consider? I will admit I don't know how it would work with the cropping, it might have to be a default crop for all images.

**Comment by fibelatti** [comment]
Hi @hughwilliams94, thanks for your feedback! I'm glad you're enjoying the app.

I'm not sure it helps, but it's already possible to share photos to the app directly from your preferred gallery app to create a new widget. This way, if your preferred gallery app has a bulk selection mechanism you can select them all and share at once. The app will import them and assume a default cropping for all images, you can then adjust the ones you may think need adjustments.

**Comment by hughwilliams94** [comment]
Thanks, that solution should work for me. In terms of storage, are images used getting copied into the app? That is, if I were to import 500 from photos would 1000 copies be stored on my device (500 original + 500 cropped copies for widget)?

18 Feb 2024 01:10:04 Filipe Belatti ***@***.***>:

**Comment by fibelatti** [comment]
@hughwilliams94 yes, they are copied because Android grants temporary access to a photo when you choose it using the standard picker, so the app creates a copy for widgets to work as expected. It does so by creating a smaller version of the original file (up to 1000x1000) for it to take way less space than the original file.

**Comment by hughwilliams94** [comment]
Thanks, I've managed to import a set of photos. The ability to monitor a folder of images so that, for example, recently taken photos could be automatically added would be great but I appreciate that the filesystem APIs might restrict that possibility.

18 Feb 2024 23:03:20 Filipe Belatti ***@***.***>:

**Comment by fibelatti** [comment]
Thanks for the suggestion, that would be handy indeed. I'll leave this issue open until I get the chance to look into it.

**Comment by fibelatti** [comment]
Hi @hughwilliams94, I have started investigating this feature and have a working prototype. I'll refine the UI to ensure that it doesn't become too confusing or overwhelming, but I expect to be able to ship this soon. Once again thanks for the suggestion and patience.

**Comment by hughwilliams94** [comment]
Thanks for having a go at implementing it, let me know if you need any testing 😀

**Comment by fibelatti** [comment]
@hughwilliams94 this feature is being shipped with version 1.6.0, rolling out in the next couple days

**Comment by hughwilliams94** [comment]
Great, looking forward to trying it out!

15 Apr 2024 01:59:42 Filipe Belatti ***@***.***>:

**Comment by hughwilliams94** [comment]
Will there be a 1.6 release via GitHub? Would you also be open to an F-Droid (https://f-droid.org) release.

**Comment by fibelatti** [comment]
@hughwilliams94 apologies, the releases page should be updated now, here's the link to the [latest one](https://github.com/fibelatti/photo-widget/releases/tag/v1.6.1).

I'll file a request to have this app included on both IzzyOnDroid and F-Droid stores
