### ISSUE TITLE
Feature request: scaling options

### ISSUE THREAD

**Issue by NickSlash** [fibelatti/photo-widget#35]
I have some tall and thin images that I've tried to create a tall widget but it zooms in (and snaps back) to +1600% to fit the width to the box which cuts off the top and bottom. 
(Example image dimensions 300h x 60w pixels)

Could something be added to snap to the height or the width for the tall and wide widgets?

**Comment by fibelatti** [comment]
Hi @NickSlash, apologies for the delayed response! At the moment the apps does that for two reasons:

- To better match the actual aspect ratio of widgets on the home screen
- To support "auto-cropping" when images are added in bulk

I'll look into adding an option to fit images with different aspect ratios but it's likely that those widgets will have empty spaces to their sides.
