### ISSUE TITLE
Crash on tapping "Rate Button"

### ISSUE THREAD

**Issue by variety754** [fibelatti/photo-widget#54]
On my Xiaomi 11T Pro running MIUI14 and Android 13, when I tap "Rate" button, the app immediately crashes. I don't have Google Play installed, but all Play links are getting directed to Aurora Store instead, so that shouldn't be the issue.

**Comment by fibelatti** [comment]
@variety754 thanks for reporting! I'll look into it to have it fixed in the next release

**Comment by fibelatti** [comment]
@variety754 I'm not familiar with the Aurora Store myself, but does it handle opening Play Store URLs, for instance https://play.google.com/store/apps/details?id=com.fibelatti.photowidget?

**Comment by variety754** [comment]
> @variety754 I'm not familiar with the Aurora Store myself, but does it handle opening Play Store URLs, for instance https://play.google.com/store/apps/details?id=com.fibelatti.photowidget?
> 
> 

It does. It for sure opens app pages and dev profiles.

**Comment by fibelatti** [comment]
@variety754 thanks for the reply. I'm gonna include a change for this in the next release, will leave this issue open until I'm sure it's fixed.

**Comment by fibelatti** [comment]
@variety754 version 1.7 was released today and this issue should be fixed. Please let me know if it isn't

**Comment by variety754** [comment]
Everything works now! Sorry for late response, I lost my Github account

**Comment by fibelatti** [comment]
@variety754 no problem, thanks for letting me know!

**Comment by variety754** [comment]
And congrats with getting on IzzySoft repository! I'm very happy for you and already downloaded your app from there
