### ISSUE TITLE
FEATURE REQUEST: Allow to add multiple Albums/Folders as a source for a single widget

### ISSUE THREAD

**Issue by Fernan181** [fibelatti/photo-widget#61]
As described above, adding the option of multiple folded/album sources on a same widget in order to easily add photos from different folders without having to copy them to another place or select all of them individually.

**Comment by fibelatti** [comment]
Hi @Fernan181, thanks for your suggestion! I have modified how synced widgets work and they will allow multiple folders starting from the next update, which should come out this weekend

**Comment by Fernan181** [comment]
Nice! Thank you so much for the quick answer! Then i guess we can close this issue. Will be checking on the update 👀.
Good luck and keep up the good work!

**Comment by fibelatti** [comment]
@Fernan181 thank you! If you have any feedback about it or more suggestions please don't hesitate to reach out again
