### ISSUE TITLE
feature request: photo frame

### ISSUE THREAD

**Issue by SeaItSelf** [fibelatti/photo-widget#92]
I want to request a feature to add frames like nothing os photo widget.
![1704431226-713493-screenshot-20240105-103637_1](https://github.com/user-attachments/assets/0cc56bfb-c9d1-4dc7-a5fa-d08ab3f21fca)

I love the app. thanks for everything 🫶🫶🫶

**Comment by fibelatti** [comment]
Hey @SeaItSelf, thanks for reaching out and submitting a suggestion!

I have considered adding support for simple frames like that, but never looked into it. I'm gonna investigate it in order to hopefully include the feature in an upcoming update.

**Comment by fibelatti** [comment]
Hi @HusniMuhammad, support for displaying text is also in my backlog but I haven't prioritized it yet. That's an interesting idea and I'll take note of it for whenever I'm working on it.

Thanks for the suggestion!

**Comment by fibelatti** [comment]
Hi @SeaItSelf, thanks for your patience! I'm happy to say that colored photo borders are finally coming in the next app update. You'll be able to apply border to any widget, except the ones that use the "Fill widget area" aspect ratio.

Thanks for your suggestion, I'll leave this issue open until a version that contains the change is released.

<img width="200" alt="image" src="https://github.com/user-attachments/assets/1c79ceea-2ec1-4b2c-8b4c-09817cf2a4fc">

**Comment by fibelatti** [comment]
Hi @SeaItSelf, this feature is included in version 1.19.0, released today. Thanks for your suggestion!
