### ISSUE TITLE
BUG: Picture resolution drops when added as widget

### ISSUE THREAD

**Issue by zun43d** [fibelatti/photo-widget#93]
I don't really know if that's a bug or not. Basically I made a class routine and put that picture as widget. Notice the image had a lot of small text. Normally the image is pretty clear. But after adding as widget I can't read text.

I am attaching the original picture and a screenshot of home screen after adding as widget.

Aspect ratio: Tall
![Screenshot of widget](https://github.com/user-attachments/assets/d2faf81b-0de2-427e-99f9-bc34f8c78ef5)
![Original picture](https://github.com/user-attachments/assets/f72fad07-5b6f-4e35-97e1-b74eb8026d51)

**Comment by SeaItSelf** [comment]
I don't know how widget itself might be causing the issue but I suggest some work arounds.

you can make the text bigger in the table you created
or
there is a option to enlarge the photo when you click on it

hope this helps

**Comment by fibelatti** [comment]
Hi @zun43d, thanks for reporting the issue! Some users had already reported loss in quality but your example definitely made my investigation easier. Without getting too technical, any image displayed on a widget must be loaded into memory first (RAM) and there's a limit to how much memory an image can use. To stay below that limit, the app downscales the image which in turn leads to quality loss (@SeaItSelf thanks for chiming in, I hope this explanation clears out how the widget causes it!)

I'm happy to say that I've made some improvements to this and used your example to verify. The image is a lot clearer after the changes, which should be released in the next couple days.

**Comment by zun43d** [comment]
Thank you so much @fibelatti for adjusting the issue. Just this was the only issue I was facing. I'm really thankful to you for this app. There are no alternatives with this many features. All the photo widget apps are loaded with ads! Eagerly waiting for the next update! 😅

**Comment by fibelatti** [comment]
Hi @zun43d, thanks for waiting patiently. The fix was included in version 1.13.2 which was released to Google Play today, and should be available in the next few hours.

I'm closing this issue as resolved, but feel free to open it again in case the issue persists.
