### ISSUE TITLE
[Feature Request]: Remove inbuild animations (as a option)

### ISSUE THREAD

**Issue by HusniMuhammad** [fibelatti/photo-widget#97]
### Describe your idea

Remove animations of this inbuild app as option to disable or fully removing this 

### Describe how you think it could work

No animations particularly **the 360° rotating animation**

### Additional context

* To improve performance on low processing devices 
*  To remove unnecessary eye irritation

**Comment by fibelatti** [comment]
Hi @HusniMuhammad, thanks for submitting your suggestion! I'm gonna include this change in the next update

**Comment by fibelatti** [comment]
@HusniMuhammad this change was included in version 1.14.0, released to Google Play Store today. The update will be available for all users in the upcoming days.

I've reduced all animations by default, so no need to configure any new options.

Thanks for suggesting it!

**Comment by HusniMuhammad** [comment]
Thanks
